In [18]:
import pandas as pd

In [19]:
data = pd.read_csv('/datasets/cs190f-public/BeerAdvocateDataset/BeerAdvocate_Train.csv')
len(data)

1269291

In [20]:
len(data)

1269291

In [3]:
test = pd.read_csv('/datasets/cs190f-public/BeerAdvocateDataset/BeerAdvocate_Test.csv')

In [5]:
len(test)

317323

In [ ]:
from torch.nn.functional import softmax
y_n = torch.FloatTensor([[0.2,0.5,0.3],[0.1,0.3,0.6],[0.7,0.25,0.15]])
softmax(y_n / cfg['temperature'], dim=1)

In [21]:
#data.dropna(subset=['beer/style'],how='any',inplace = True)
data.dropna(subset=['review/overall', 'beer/style', 'review/text'],how='any',inplace = True)

In [26]:
data = data['review/text'].tolist()

In [ ]:
d = [d.split() for d in data]

In [3]:
'happy/'+'e%dcount%d'%(1,2)

'happy/e1count2'

In [2]:
from random import shuffle
import numpy as np
a = np.arange(5)
shuffle(a)
a

array([3, 4, 2, 0, 1])

In [1]:
import torch
tensor = torch.tensor(())
t = tensor.new_zeros((3,3,3))
t[[[0],[1],[2]],[0,1,2],[[0,0,1],[1,2,0],[0,2,1]]]= 1
#t[np.arange(3), :, [0,1,2]] = 1
t

tensor([[[ 1.,  0.,  0.],
         [ 1.,  0.,  0.],
         [ 0.,  1.,  0.]],

        [[ 0.,  1.,  0.],
         [ 0.,  0.,  1.],
         [ 1.,  0.,  0.]],

        [[ 1.,  0.,  0.],
         [ 0.,  0.,  1.],
         [ 0.,  1.,  0.]]])

In [16]:
input_t = t[0,[0],:].unsqueeze_(0)

In [17]:
input_t.size()

torch.Size([1, 1, 3])

In [6]:
label = torch.zeros(5, 3, dtype=torch.long)

In [12]:
 n_indices = torch.zeros((5, 1), dtype=torch.long)
batch_arange = torch.arange(5, dtype=torch.long)
n_indices[batch_arange,0] = batch_arange
seq_arange = torch.arange(3, dtype=torch.long)
label[n_indices, seq_arange] = torch.LongTensor([[56,30,11],[2,5,5],[3,4,4],[7,8,8],[9,10,10]])

In [13]:
label

tensor([[ 56,  30,  11],
        [  2,   5,   5],
        [  3,   4,   4],
        [  7,   8,   8],
        [  9,  10,  10]])

In [15]:
label[:,0]

tensor([ 56,   2,   3,   7,   9])

In [11]:
b = torch.tensor(())
b = b.new_zeros((5,1))
b[np.arange(5),0] = torch.FloatTensor([1,2,3,4,5])

In [12]:
b

tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.]])

In [28]:
label = torch.zeros(2, 5, dtype=torch.long)
label[[[0],[1]], np.arange(5)] = torch.tensor([[1,2,3],[4,5,3],[4,5,1,2]])

In [29]:
label

tensor([[ 1,  2,  3,  4,  5],
        [ 3,  4,  5,  1,  2]])

In [73]:
a = [[0],[1,2],[0,3,5]]
for i in a:
    i += (3-len(i))*[-1]
    

In [74]:
a

[[0, -1, -1], [1, 2, -1], [0, 3, 5]]

In [59]:
import numpy as np
a = np.zeros((4,1),dtype=int)
a[np.arange(4),0] = np.arange(4)
a

array([[0],
       [1],
       [2],
       [3]])

In [78]:
a = torch.FloatTensor([[1,0,0],[0,1,2]])
(a[:,2] + 100).long()

tensor([ 100,  102])

In [5]:
styles = data['beer/style'].unique()
print(styles)
print(len(styles))

['Hefeweizen' 'English Strong Ale' 'Foreign / Export Stout'
 'German Pilsener' 'American Double / Imperial IPA' 'Herbed / Spiced Beer'
 'Oatmeal Stout' 'American Pale Lager' 'Rauchbier'
 'American Pale Ale (APA)' 'American Porter' 'Belgian Strong Dark Ale'
 'American Stout' 'Russian Imperial Stout' 'American Amber / Red Ale'
 'American Strong Ale' 'Märzen / Oktoberfest' 'American Adjunct Lager'
 'American Blonde Ale' 'American IPA' 'Fruit / Vegetable Beer'
 'American Double / Imperial Stout' 'English Bitter' 'English Porter'
 'Irish Dry Stout' 'American Barleywine' 'Belgian Strong Pale Ale'
 'Doppelbock' 'Maibock / Helles Bock' 'Light Lager' 'Pumpkin Ale'
 'Dortmunder / Export Lager' 'Euro Strong Lager' 'Euro Dark Lager'
 'Low Alcohol Beer' 'Euro Pale Lager' 'Bock'
 'English India Pale Ale (IPA)' 'Altbier' 'Kölsch' 'Munich Dunkel Lager'
 'Rye Beer' 'American Pale Wheat Ale' 'Milk / Sweet Stout' 'Schwarzbier'
 'Vienna Lager' 'American Amber / Red Lager' 'Scottish Ale' 'Witbier'
 'Saison

In [6]:
ratings = data['review/overall'].unique()
print(ratings)
print(len(ratings))

[1.5 3.  4.  3.5 4.5 5.  2.  2.5 1.  0. ]
10
